-- Constraints

-- Column and Table Constraints:
    --
     CREATE TABLE natural_example (
       animal_id text CONSTRAINT animal_key PRIMARY KEY,
     );
 -- vs 
    --
     CREATE TABLE natural_example (
       animal_id text,
       CONSTRAINT animal_key PRIMARY KEY (animal_id),
     );
    -- Adding and Dropping Constraints
      ALTER TABLE natural_example DROP CONSTRAINT animal_key;
      ALTER TABLE natural_example ADD CONSTRAINT animal_key PRIMARY KEY (animal_id);
    
-- Primary Keys
  -- Must be UNIQUE and NOT NULL. You could use the same for another column, example: 
    -- email text CONSTRAINT email_unique UNIQUE
    -- column_name text NOT NULL
    
  -- Key could be generated by itself (or use BIGSERIAL data type):
    --
       CREATE TABLE surrogate_key_example (
           order_number bigint GENERATED ALWAYS AS IDENTITY,
           product_name text,
           order_time timestamp with time zone,
           CONSTRAINT order_number_key PRIMARY KEY (order_number)
       );
    
    -- If you manually insert data, you always can restart the sequence:
      --
         INSERT INTO surrogate_key_example
         OVERRIDING SYSTEM VALUE
         VALUES (4, 'Chicken Coop', '2021-09-03 10:33-07');
         
         ALTER TABLE surrogate_key_example ALTER COLUMN order_number RESTART WITH 5;
         
         INSERT INTO surrogate_key_example (product_name, order_time)
         VALUES ('Aloe Plant', '2020-03-15 10:09-07');

  
-- Composite Primary Key:
  --
     CREATE TABLE natural_key_composite_example (
         student_id text,
         school_day date,
         present boolean,
         CONSTRAINT student_key PRIMARY KEY (student_id, school_day)
     );

-- Foreign keys
  -- Must exist in the main table.
     CREATE TABLE licenses (
        license_id text,
        first_name text,
        last_name text,
        CONSTRAINT licenses_key PRIMARY KEY (license_id)
     );

     CREATE TABLE registrations (
        registration_id text,
        registration_date timestamp with time zone,
        license_id text REFERENCES licenses (license_id),
        CONSTRAINT registration_key PRIMARY KEY (registration_id, license_id)
     );

     INSERT INTO licenses (license_id, first_name, last_name)
     VALUES ('T229901', 'Steve', 'Rothery');

     INSERT INTO registrations (registration_id, registration_date, license_id)
     VALUES ('A203391', '2022-03-17', 'T229901');
     
     -- Error (there isn't a license_id with that value):
     -- INSERT INTO registrations (registration_id, registration_date, license_id)
     -- VALUES ('A75772', '2022-03-17', 'T000001');

-- Check
-- Constraints to validate if given data can be added.
    -- CONSTRAINT check_role_in_list CHECK (user_role IN('Admin', 'Staff'))
    -- CONSTRAINT check_salary_not_below_zero CHECK (salary >= 0)
